-- ===========================================
-- 0. PROFILES – jediný účet pro login/auth
-- ===========================================
CREATE TABLE profiles (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name VARCHAR(255) NOT NULL,
                          last_name VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL,
                          password VARCHAR(255) NOT NULL,
                          date_of_birth DATE NOT NULL,

                          role VARCHAR(20) NOT NULL DEFAULT 'USER',
                          CONSTRAINT chk_profiles_role CHECK (role IN ('USER','ADMIN', 'HOTEL_OWNER')),

                          is_verified BOOLEAN NOT NULL DEFAULT FALSE,
                          two_factor_email BOOLEAN NOT NULL DEFAULT FALSE,
                          verification_code VARCHAR(100),
                          verification_code_expiration TIMESTAMP,
                          created_at TIMESTAMP NOT NULL DEFAULT now(),
                          updated_at TIMESTAMP NOT NULL DEFAULT now(),
                          avatar_id BIGINT
);

ALTER TABLE profiles ADD CONSTRAINT profiles_email_key UNIQUE (email);
CREATE INDEX idx_profiles_lower_l_name ON profiles (LOWER(last_name));
CREATE INDEX idx_profiles_lower_f_name ON profiles (LOWER(first_name));

-- ===========================================
-- 1. AVATARS – historie avatarů + aktuální přes profiles.avatar_id
-- ===========================================
CREATE TABLE avatars (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         image_url TEXT NOT NULL,
                         public_id TEXT NOT NULL,
                         created_at TIMESTAMP NOT NULL DEFAULT now(),
                         profile_id BIGINT NOT NULL,
                         CONSTRAINT fk_avatars_profile
                             FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE INDEX idx_avatars_profile_id ON avatars(profile_id);

ALTER TABLE profiles
    ADD CONSTRAINT fk_profiles_avatar
        FOREIGN KEY (avatar_id) REFERENCES avatars(id) ON DELETE SET NULL;

-- ===========================================
-- 2. USERS – detail běžného uživatele (shared PK)
-- ===========================================
CREATE TABLE users (
                       profile_id BIGINT PRIMARY KEY,
                       CONSTRAINT fk_users_profile
                           FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
                       num_of_bookings INT NOT NULL DEFAULT 0
);

-- ===========================================
-- 3. ADMINS – detail admina (shared PK)
-- ===========================================
CREATE TABLE admins (
                        profile_id BIGINT PRIMARY KEY,
                        CONSTRAINT fk_admins_profile
                            FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE TABLE hotel_owners (
                        profile_id BIGINT PRIMARY KEY,
                        num_of_hotels INTEGER NOT NULL DEFAULT 0,
                        CONSTRAINT fk_hotel_owners_profile
                            FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);