-- ===========================================
-- 4. HOTELS – každý hotel může mít více rooms
-- ===========================================
CREATE TABLE hotels (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        description TEXT,
                        created_at TIMESTAMP NOT NULL DEFAULT now(),
                        updated_at TIMESTAMP NOT NULL DEFAULT now(),
                        hotel_owner_id BIGINT NOT NULL,
                        likes INTEGER NOT NULL DEFAULT 0,
                        num_of_rooms INTEGER NOT NULL DEFAULT 0,
                        ratings_count INTEGER NOT NULL DEFAULT 0,
                        rating INTEGER NOT NULL DEFAULT 0,
                        CONSTRAINT fk_rooms_hotel_owner
                            FOREIGN KEY (hotel_owner_id) REFERENCES hotel_owners(profile_id) ON DELETE CASCADE,
                        CONSTRAINT chk_room_rating CHECK (rating BETWEEN 0 AND 5)
);

CREATE INDEX idx_hotels_name ON hotels (LOWER(name));

CREATE TABLE locations (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           country VARCHAR(100) NOT NULL,
                           city VARCHAR(100) NOT NULL,
                           street VARCHAR(255),
                           street_number VARCHAR(20) NOT NULL,
                           postal_code VARCHAR(20),
                           hotel_id BIGINT NOT NULL,
                           CONSTRAINT uq_location UNIQUE (country, city, street, street_number),
                           CONSTRAINT fk_location_hotel FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE
);


CREATE TABLE hotel_images (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              image_url TEXT NOT NULL,
                              public_id TEXT NOT NULL,
                              created_at TIMESTAMP NOT NULL DEFAULT now(),
                              hotel_id BIGINT NOT NULL,
                              CONSTRAINT fk_hotel_images_hotel
                                  FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE
);

CREATE INDEX idx_hotel_images_hotel_id ON hotel_images(hotel_id);
-- ===========================================
-- 5. ROOMS – pokoje
-- ===========================================
CREATE TABLE rooms (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       description TEXT NOT NULL,
                       room_type VARCHAR(255) NOT NULL,
                       room_price DECIMAL NOT NULL,
                       is_booked BOOLEAN NOT NULL DEFAULT FALSE,
                       hotel_id BIGINT NOT NULL,
                       room_number BIGINT NOT NULL,
                       capacity BIGINT NOT NULL,
                       /*CONSTRAINT fk_rooms_hotel_owner
                           FOREIGN KEY (hotel_owner_id) REFERENCES hotel_owners(profile_id) ON DELETE CASCADE,*/
                       CONSTRAINT fk_rooms_hotels
                           FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
                       CONSTRAINT uq_hotel_room UNIQUE (hotel_id, room_number)
);

CREATE INDEX idx_rooms_hotel_id ON rooms(hotel_id);

CREATE TABLE room_images (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             image_url TEXT NOT NULL,
                             public_id TEXT NOT NULL,
                             created_at TIMESTAMP NOT NULL DEFAULT now(),
                             room_id BIGINT NOT NULL,
                             CONSTRAINT fk_room_images_room
                                 FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE INDEX idx_room_images_room_id ON room_images(room_id);

-- ===========================================
-- 6. BOOKINGS – rezervace
-- ===========================================
CREATE TABLE bookings (
                          booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          check_in DATE NOT NULL,
                          check_out DATE NOT NULL,
                          guest_full_name VARCHAR(255) NOT NULL,
                          guest_email VARCHAR(255) NOT NULL,
                          user_id BIGINT NOT NULL,
                          adults INT NOT NULL,
                          children INT NOT NULL,
                          total_guests INT NOT NULL,
                          booking_confirmation_code VARCHAR(100),
                          room_id BIGINT NOT NULL,
                          CONSTRAINT fk_booking_on_room
                              FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
                          CONSTRAINT fk_bookings_user
                              FOREIGN KEY (user_id) REFERENCES users(profile_id) ON DELETE CASCADE
);

CREATE INDEX idx_bookings_room_id ON bookings(room_id);
CREATE INDEX idx_bookings_dates ON bookings(check_in, check_out);
CREATE INDEX idx_bookings_profile_id ON bookings(user_id);


