-- ===========================================
-- 7. LIKED_ROOMS – oblíbené pokoje (surrogate key)
-- ===========================================



CREATE TABLE liked_hotels (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id BIGINT NOT NULL,
                             hotel_id BIGINT NOT NULL,
                             liked_at TIMESTAMP NOT NULL DEFAULT now(),


                             CONSTRAINT uk_liked_hotels_user_hotel UNIQUE (user_id, hotel_id),

                             CONSTRAINT fk_liked_hotels_user
                                 FOREIGN KEY (user_id) REFERENCES users(profile_id) ON DELETE CASCADE,

                             CONSTRAINT fk_liked_hotels_hotel
                                 FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE
);

-- Indexy pro rychlé vyhledávání
CREATE INDEX idx_liked_hotels_user_id ON liked_hotels(user_id);
CREATE INDEX idx_liked_hotels_hotel_id ON liked_hotels(hotel_id);

-- ===========================================
-- 8. RATINGS – hodnocení pokojů (surrogate key)
-- ===========================================
CREATE TABLE ratings (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id BIGINT NOT NULL,
                         hotel_id BIGINT NOT NULL,
                         rating INTEGER NOT NULL DEFAULT 0,
                         comment TEXT DEFAULT NULL,
                         created_at TIMESTAMP NOT NULL DEFAULT now(),

    -- unique constraint místo composite PK
                         CONSTRAINT uk_ratings_user_hotel UNIQUE (user_id, hotel_id),
                         CONSTRAINT chk_room_rating CHECK (rating BETWEEN 0 AND 5),

                         CONSTRAINT fk_ratings_user
                             FOREIGN KEY (user_id) REFERENCES users(profile_id) ON DELETE CASCADE,

                         CONSTRAINT fk_ratings_hotel
                             FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE
);

-- Indexy pro rychlé vyhledávání
CREATE INDEX idx_ratings_user_id ON ratings(user_id);
CREATE INDEX idx_ratings_hotel_id ON ratings(hotel_id);